### ISSUE TITLE
Tp ended

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/4a-isi3-tp1-2016-2017-groupe-2-petitcuenot-dolle#1]
* 💡 pourquoi créer des variables dans addEdge ?

* ⚠️ Où est le lien entre UndirectedGraph et Graph dans votre UML, c'est le coeur du problème

* ⚠️ retourner un null pour votre getNextNode c'est pas super, je suis sur que vous pouvez trouver autrement.

* 👍 Adapteur + Iterator

* ⚠️ Je trouve l'indentation dans GraphIterator.next() un peu fuckesque, De plus, pitié mais adjs c'est pas un nom de variable.
D'ailleurs, vous pouvez trouver à ne pas construire cette variable est directement itérer sur votre list d'adjacents sans les collecter (chercher un peu de doc)

* 💡 Il faut éviter les return null en java, ça va vous poser des problèmes

**Comment by JeremyDolle** [comment]
Normalement tout a été corrigé, merci pour tout les conseils 👍

**Comment by Slashgear** [comment]
👌
